version: "3.7"

secrets:
  cloudflare_acme:
    external: true

services:
  traefik:
    image: "traefik:v2.4.5"
    command:
      - "--log.level=DEBUG"
      - "--accesslog=true"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.traefik.address=:8080"
      - "--entryPoints.http.address=:80"
      - "--entryPoints.https.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.email=me@dchr.host"
      - "--certificatesresolvers.letsencrypt.acme.storage=/etc/traefik/certs/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.dnsChallenge.provider=cloudflare"
      - "--certificatesresolvers.letsencrypt.acme.dnsChallenge.resolvers=1.1.1.1:53,1.0.0.1:53"
    environment:
      - "CF_DNS_API_TOKEN_FILE=/run/secrets/cloudflare_acme"
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/traefik:/etc/traefik
    secrets:
      - cloudflare_acme
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.middlewares.http-to-https.redirectscheme.scheme=https"
        - "traefik.http.middlewares.http-to-https.redirectscheme.permanent=true"
        - "traefik.http.routers.public-http.entrypoints=http"
        - "traefik.http.routers.public-http.rule=HostRegexp(`{domain:.*}`)"
        - "traefik.http.routers.public-http.middlewares=http-to-https"
        - "traefik.http.services.traefik.loadbalancer.server.port=443"
    networks:
      - traefik-public
      - lioctad-dev
      - lioctad

networks:
  lioctad-dev:
    external: true
  lioctad:
    external: true
  traefik-public:
    external: true