name: LIO Build/Test

on:
  push:
    branches: [ master ]
    paths: [ 'src/**/*.go', 'src/go.*', 'src/vendor/**' ]
  pull_request:
    branches: [ '*' ]
    paths: [ 'src/**/*.go', 'src/go.*', 'src/vendor/**' ]

env:
  DEV_CRYPTO_KEY: testkeyforthelioctadcryptosystem

jobs:

  lio-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: cd src/cmd/lio && go build -v -o lio

  lio-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Test
        run: cd src && go test -parallel 4 -shuffle on -race -v ./...
